# ----
# Site

title: Steem Developer
description: Steem Developer Documentation.
url: https://developer.steem.io
google_analytics_key:
permalink: /:categories/:title.html

collections:
  introduction:
    title: Introduction
    id: introduction
    position: 1
    output: true
  quickstart:
    title: Quickstart
    id: quickstart
    position: 2
    output: true
  javascript:
    title: Javascript
    id: javascript
    position: 3
    output: true
  tutorials:
    title: Tutorials
    id: tutorials
    position: 5
    output: true
  services:
    title: Services
    id: services
    position: 6
    output: true
  community:
    title: Community
    id: community
    position: 7
    output: true
  glossary:
    title: Glossary
    id: glossary
    position: 8
    output: true
  tutorials-javascript:
    title: Javascript Tutorials
    id: tutorials-javascript
    position: 9
    output: true
  tutorials-python:
    title: Python Tutorials
    id: tutorials-python
    position: 10
    output: true
  apidefinitions:
    title: API Definitions
    id: apidefinitions
    position: 11
    output: true
  testnet:
    title: Testnet
    id: testnet
    position: 12
    output: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - vendor
  - Makefile

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post

kramdown:
  auto_ids: true
  
