# ----
# Site

title: Steem Developer
description: Steem Developer Documentation.
url: https://developer.steem.io
google_analytics_key:
permalink: pretty

collections:
  introduction:
    title: Introduction
    position: 1
  piston:
    title: Piston
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - vendor
  - Makefile

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
