# ----
# Site

title: Steem Developer
description: Steem Developer Documentation.
url: https://developer.steem.io
google_analytics_key:
permalink: /:categories/:title.html

collections:
  introduction:
    title: Introduction
    position: 1
  quickstart:
    title: Quickstart
    position: 2
  javascript:
    title: Javascript
    position: 3
  python:
    title: Python
    position: 4
  services:
    title: Services
    position: 5
  resources:
    title: Resources
    position: 6
  community:
    title: Community
    position: 7


gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - vendor
  - Makefile

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
